# Generated by Django 3.0.6 on 2020-07-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200712_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('prime_status', models.CharField(default='', max_length=50)),
                ('field', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=700)),
            ],
        ),
    ]
